Repository do-kevin/Project-Two, pull requests merged in 2018-10, with the labels that each got.

#4 schema for database added, spawn enemy function created but not working
  assets/javascript/game.js
  index.html
  schema.sql
Labels: awesome

#38 Bulma css
  public/assets/css/style.css
  public/assets/javascript/game.js
  public/index.html
Labels: bug

#41 Adds Michael, SFX, pictures & modal
  public/assets/audio/coinflip.mp3
  public/assets/audio/michael-compliment1.mp3
  public/assets/audio/michael-compliment2.mp3
  public/assets/audio/michael-sad.mp3
  public/assets/audio/michael-welcome1.mp3
  public/assets/audio/michael-welcome2.mp3
  public/assets/audio/nope.mp3
  public/assets/css/style.css
  public/assets/img/game-over.png
  public/assets/img/michael-shopkeeper1.png
  public/assets/img/victory.png
  public/assets/javascript/game.js
  public/index.html
Labels: bug, enhancement

#47 Restyles the creator page
  public/assets/audio/cat-punches.mp3
  public/assets/audio/defend-parry.mp3
  public/assets/audio/michael-compliment1.mp3
  public/assets/audio/michael-compliment1.wav
  public/assets/audio/michael-compliment2.mp3
  public/assets/audio/michael-compliment2.wav
  public/assets/audio/michael-sad.mp3
  public/assets/audio/michael-sad.wav
  public/assets/audio/michael-welcome.mp3
  public/assets/audio/michael-welcome.wav
  public/assets/audio/michael-welcome1.mp3
  public/assets/audio/michael-welcome2.mp3
  public/assets/audio/stunned.mp3
  public/assets/css/style.css
  public/assets/img/GitHub-Mark-64px.png
  public/assets/javascript/game.js
  public/index.html
  routes/api-routes.js
Labels: enhancement

#49 Animates character creator and adds angry lines
  public/assets/audio/drink-potion.mp3
  public/assets/audio/michael-addict.mp3
  public/assets/audio/michael-angry1.mp3
  public/assets/audio/michael-angry2.mp3
  public/assets/audio/michael-congratz-1.mp3
  public/assets/audio/michael-congratz-2.mp3
  public/assets/audio/michael-congratz-3.mp3
  public/assets/audio/michael-cooldown-1.mp3
  public/assets/audio/michael-cooldown-2.mp3
  public/assets/audio/michael-cooldown-3.mp3
  public/assets/audio/michael-cooldown-4.mp3
  public/assets/css/style.css
  public/assets/img/skull-favicon.png
  public/assets/javascript/game.js
  public/index.html
Labels: awesome
